name: check_radio_group
description: Custom Radio Buttom and Checkbox Group for all with simple usage.
version: 2.0.2
homepage: https://github.com/caiubitech/check_radio_group

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
